### ISSUE TITLE
Add DNS record for geodetic-v1.isotc211.org to point to GitHub Pages of https://github.com/isogr/register-system-transition

### ISSUE THREAD

**Issue by ribose-jeffreylau** [isogr/register-system-transition#57]
## Background

We are on the verge of switching over to the new ISO GR registry.  Switching over requires the record for `geodetic.isotc211.org` to point to GitHub Pages of `https://github.com/isogr/registry`, but before that can happen, `geodetic-v1.isotc211.org` needs to be created to point to GitHub Pages of `https://github.com/isogr/register-system-transition`

## Expected result

- Visiting `geodetic-v1.isotc211.org` should go to the GitHub Pages of `https://github.com/isogr/register-system-transition`.
- _**(unchanged)**_ Visiting `geodetic.isotc211.org` should go to the GitHub Pages of `https://github.com/isogr/register-system-transition`.
- _**(unchanged)**_ Visiting `geodetic-v2.isotc211.org` should go to the GitHub Pages of `https://github.com/isogr/registry`.

**Comment by kwkwan** [comment]
@ribose-jeffreylau Github Page custom domain can only serve one domain for one repo.  Thus, you cannot have two domains pointing to the same GHP site.

**Comment by ribose-jeffreylau** [comment]
@kwkwan I see.  Are we able to add a CNAME redirect from `geodetic.isotc211.org` to `geodetic-v1.isotc211.org`?

**Comment by kwkwan** [comment]
@ribose-jeffreylau A CNAME record of `geodetic-v1.isotc211.org` is not appropriate for the redirection.  It is because GHP site will generate a SSL certificate because on the full domain name (e.g. `geodetic.isotc211.org`).  When you use CNAME to  redirect from `geodetic-v1.isotc211.org` to `geodetic.isotc211.org`, the name of SSL certificate will not be matched.

A DNS redirection (the domain name in the address of the browser will also be changed) will be a better solution, however, it is only available in GoDaddy.

So, you may consider to keep two domain names only:
- `geodetic.isotc211.org` will point to `https://github.com/isogr/register-system-transition`
- `geodetic-v2.isotc211.org` will point to `https://github.com/isogr/registry`

**Comment by ribose-jeffreylau** [comment]
Thanks @kwkwan , so I guess the best way would be to just do all the switches in one go, in the following order, when the time comes.

I.e.,

1. Set GHP of `https://github.com/isogr/register-system-transition` to `geodetic-v1.isotc211.org`
1. Set GHP of `https://github.com/isogr/registry` to `geodetic.isotc211.org`

**Comment by kwkwan** [comment]
@ribose-jeffreylau Yes, please notice me when the time comes.

**Comment by ribose-jeffreylau** [comment]
@kwkwan We are ready to make the switch.  Thanks!

> Set GHP of `https://github.com/isogr/register-system-transition` to `geodetic-v1.isotc211.org`

**Comment by ronaldtse** [comment]
@ribose-jeffreylau can you make the change yourself? Do you mean `register-system-transition` or `register`?

Before going live we also should change to use the `main` branch instead of `master`.

**Comment by ronaldtse** [comment]
Actually @kwkwan needs to make the switch since it involves DNS.

**Comment by kwkwan** [comment]
@ribose-jeffreylau DNS updated
Set GHP of https://github.com/isogr/register-system-transition to geodetic-v1.isotc211.org
Set GHP of https://github.com/isogr/registry to geodetic.isotc211.org

However, the page of https://geodetic.isotc211.org shows:

```
Failed to load extension or dataset

A networking error is a likely cause.
Reloading the page may help.
More (probably unhelpful) details below.

(FiberFailure) Error: Database is in use by another tab, please close it, undefined
```

Please check.

**Comment by ribose-jeffreylau** [comment]
Thanks @kwkwan !
